# Generated by Django 5.2.5 on 2025-08-27 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructor_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'revenues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='instructorrevenue',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorrevenue',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='instructorrevenue',
            name='payout',
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_created_at_fd23b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='refund',
            name='refunds_payment_status_9393e2_idx',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='current_usage_count',
            new_name='current_uses',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='usage_limit',
            new_name='max_uses',
        ),
        migrations.RenameField(
            model_name='instructorpayout',
            old_name='payment_details',
            new_name='gateway_response',
        ),
        migrations.RenameField(
            model_name='instructorpayout',
            old_name='payout_amount',
            new_name='gross_revenue',
        ),
        migrations.RenameField(
            model_name='instructorpayout',
            old_name='platform_fee',
            new_name='net_amount',
        ),
        migrations.RenameField(
            model_name='instructorpayout',
            old_name='admin_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='instructorpayout',
            old_name='total_revenue',
            new_name='platform_commission',
        ),
        migrations.RenameField(
            model_name='instructorpayout',
            old_name='completed_at',
            new_name='processed_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='gateway_transaction_id',
            new_name='external_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='gateway',
            new_name='failure_code',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='completed_at',
            new_name='processed_at',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='admin_notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='gateway_refund_id',
            new_name='external_refund_id',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='completed_at',
            new_name='processed_at',
        ),
        migrations.RenameIndex(
            model_name='instructorpayout',
            new_name='instructor__instruc_a5d585_idx',
            old_name='payouts_instructor_status_9393e2_idx',
        ),
        migrations.RenameIndex(
            model_name='instructorpayout',
            new_name='instructor__period__47aec4_idx',
            old_name='payouts_period_range_b02db0_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_user_id_17dbdf_idx',
            old_name='orders_user_id_9393e2_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_order_n_1336be_idx',
            old_name='orders_order_number_b02db0_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_created_b25042_idx',
            old_name='orders_created_at_fd23b8_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_order_i_3d4604_idx',
            old_name='payments_order_status_9393e2_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_payment_2d1dd8_idx',
            old_name='payments_payment_id_b02db0_idx',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='maximum_discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='instructorpayout',
            unique_together={('instructor', 'period_start', 'period_end')},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reason_description',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_courses',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount'), ('free_course', 'Free Course')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='external_payout_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='payout_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='payout_method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(choices=[('customer_request', 'Customer Request'), ('course_cancelled', 'Course Cancelled'), ('technical_issue', 'Technical Issue'), ('policy_violation', 'Policy Violation'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'order')},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'valid_from', 'valid_until'], name='coupons_status_3e0e06_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created_by'], name='coupons_created_c3c2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='coupon_usag_coupon__4d4fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_at'], name='coupon_usag_used_at_252e58_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorpayout',
            index=models.Index(fields=['payout_id'], name='instructor__payout__8ba702_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_payment_id'], name='payments_externa_46a519_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_id'], name='refunds_refund__ee280b_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'created_at'], name='refunds_status_df4b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='refunds_payment_0cace6_idx'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenue',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='payments.orderitem'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='payments.instructorpayout'),
        ),
        migrations.DeleteModel(
            name='InstructorRevenue',
        ),
        migrations.RemoveField(
            model_name='instructorpayout',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='instructorpayout',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['instructor', 'is_paid'], name='revenues_instruc_33bb19_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['created_at'], name='revenues_created_a8e844_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['payout'], name='revenues_payout__d1b21b_idx'),
        ),
    ]
