# Generated by Django 5.2.5 on 2025-08-27 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'poll_responses',
            },
        ),
        migrations.CreateModel(
            name='SessionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('message', 'Message'), ('question', 'Question'), ('answer', 'Answer'), ('poll', 'Poll'), ('announcement', 'Announcement')], default='message', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'session_chat',
                'ordering': ['sent_at'],
            },
        ),
        migrations.RemoveField(
            model_name='sessionchatmessage',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='sessionchatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='sessionchatmessage',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='sessionpollresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionpollresponse',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='sessionpollresponse',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='sessionrecording',
            options={},
        ),
        migrations.RenameField(
            model_name='sessionpoll',
            old_name='ended_at',
            new_name='closed_at',
        ),
        migrations.RenameField(
            model_name='sessionrecording',
            old_name='download_url',
            new_name='external_url',
        ),
        migrations.RenameField(
            model_name='sessionrecording',
            old_name='is_processed',
            new_name='is_public',
        ),
        migrations.RenameIndex(
            model_name='livesession',
            new_name='live_sessio_course__b4f7d9_idx',
            old_name='live_sessions_course_status_idx',
        ),
        migrations.RenameIndex(
            model_name='livesession',
            new_name='live_sessio_instruc_149253_idx',
            old_name='live_sessions_instructor_schedule_idx',
        ),
        migrations.RenameIndex(
            model_name='livesession',
            new_name='live_sessio_schedul_604203_idx',
            old_name='live_sessions_schedule_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionattendance',
            new_name='session_att_session_73faca_idx',
            old_name='session_attendances_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionattendance',
            new_name='session_att_student_74c5b5_idx',
            old_name='session_attendances_student_status_idx',
        ),
        migrations.RemoveField(
            model_name='sessionpoll',
            name='poll_type',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='external_recording_id',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='file_size_bytes',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='sessionrecording',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sessionpoll',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='file_size_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recording_thumbnails/'),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='session_recordings/'),
        ),
        migrations.AlterField(
            model_name='sessionpoll',
            name='options',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sessionpoll',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='processing_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='live_sessions.sessionpoll'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionchat',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='live_sessions.sessionchat'),
        ),
        migrations.AddField(
            model_name='sessionchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionchat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live_sessions.livesession'),
        ),
        migrations.DeleteModel(
            name='SessionChatMessage',
        ),
        migrations.DeleteModel(
            name='SessionPollResponse',
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('poll', 'student')},
        ),
        migrations.AddIndex(
            model_name='sessionchat',
            index=models.Index(fields=['session', 'sent_at'], name='session_cha_session_40c9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionchat',
            index=models.Index(fields=['sender'], name='session_cha_sender__20ac6e_idx'),
        ),
    ]
