# Generated by Django 5.2.5 on 2025-08-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticssnapshot',
            new_name='analytics_s_snapsho_986962_idx',
            old_name='analytics_s_snapsho_9393e2_idx',
        ),
        migrations.RenameIndex(
            model_name='coursemetrics',
            new_name='course_metr_course__d8b84a_idx',
            old_name='course_metr_course__b02db0_idx',
        ),
        migrations.RenameIndex(
            model_name='coursemetrics',
            new_name='course_metr_date_33e86b_idx',
            old_name='course_metr_date_fd23b8_idx',
        ),
        migrations.RenameIndex(
            model_name='instructormetrics',
            new_name='instructor__instruc_cca5b4_idx',
            old_name='instructor__instruc_9393e2_idx',
        ),
        migrations.RenameIndex(
            model_name='instructormetrics',
            new_name='instructor__date_e41b64_idx',
            old_name='instructor__date_fd23b8_idx',
        ),
        migrations.RenameIndex(
            model_name='platformmetrics',
            new_name='platform_me_date_5e991f_idx',
            old_name='platform_me_date_fd23b8_idx',
        ),
        migrations.RenameIndex(
            model_name='platformmetrics',
            new_name='platform_me_date_4c041d_idx',
            old_name='platform_me_date_9393e2_idx',
        ),
        migrations.RenameIndex(
            model_name='studentmetrics',
            new_name='student_met_student_295a96_idx',
            old_name='student_met_student_b02db0_idx',
        ),
        migrations.RenameIndex(
            model_name='studentmetrics',
            new_name='student_met_date_452cf3_idx',
            old_name='student_met_date_fd23b8_idx',
        ),
    ]
