# Generated by Django 5.2.5 on 2025-08-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menuclicktracking',
            new_name='navigation__menu_it_063313_idx',
            old_name='navigation_menu_item_clicked_at_idx',
        ),
        migrations.RenameIndex(
            model_name='menuclicktracking',
            new_name='navigation__user_id_7b138d_idx',
            old_name='navigation_user_clicked_at_idx',
        ),
        migrations.RenameIndex(
            model_name='menuclicktracking',
            new_name='navigation__clicked_58d30f_idx',
            old_name='navigation_clicked_at_idx',
        ),
    ]
