# Generated by Django 5.2.5 on 2025-08-27 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('course_enrollment', 'Course Enrollment'), ('course_review', 'Course Review'), ('assignment_due', 'Assignment Due'), ('payment_confirmation', 'Payment Confirmation'), ('certificate_awarded', 'Certificate Awarded'), ('forum_reply', 'Forum Reply'), ('password_reset', 'Password Reset'), ('account_activation', 'Account Activation')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_course_updates', models.BooleanField(default=True)),
                ('email_assignments', models.BooleanField(default=True)),
                ('email_forum_activity', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('in_app_course_updates', models.BooleanField(default=True)),
                ('in_app_assignments', models.BooleanField(default=True)),
                ('in_app_forum_activity', models.BooleanField(default=True)),
                ('in_app_payments', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('push_course_updates', models.BooleanField(default=True)),
                ('push_assignments', models.BooleanField(default=True)),
                ('push_forum_activity', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('enrollment', 'Enrollment'), ('review', 'Review'), ('assignment', 'Assignment'), ('course_update', 'Course Update'), ('payment', 'Payment'), ('certificate', 'Certificate'), ('forum', 'Forum'), ('system', 'System')], default='info', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
