# Generated by Django 5.2.5 on 2025-08-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.userrecommendationprofile')),
            ],
            options={
                'db_table': 'user_viewed_courses',
                'verbose_name': 'User Viewed Course',
                'verbose_name_plural': 'User Viewed Courses',
            },
        ),
        migrations.AddField(
            model_name='userrecommendationprofile',
            name='viewed_courses',
            field=models.ManyToManyField(blank=True, related_name='viewed_by_users', through='recommendations.UserViewedCourse', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='userviewedcourse',
            index=models.Index(fields=['user_profile', 'last_viewed'], name='user_viewed_user_pr_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='userviewedcourse',
            index=models.Index(fields=['course', 'last_viewed'], name='user_viewed_course__2b3c4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userviewedcourse',
            unique_together={('user_profile', 'course')},
        ),
    ]