# Generated by Django 5.2.5 on 2025-08-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_add_user_viewed_course'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_user_id_e533fa_idx',
            old_name='recommendat_user_id_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_user_id_373e78_idx',
            old_name='recommendat_user_id_5e6f7g_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_generat_c45ce2_idx',
            old_name='recommendat_generat_6f7g8h_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_score_11d775_idx',
            old_name='recommendat_score_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationfeedback',
            new_name='recommendat_recomme_0289fd_idx',
            old_name='recommendat_recomme_8h9i0j_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationfeedback',
            new_name='recommendat_user_id_8fc6e1_idx',
            old_name='recommendat_user_id_9i0j1k_idx',
        ),
        migrations.RenameIndex(
            model_name='usercourseinteraction',
            new_name='user_course_user_id_8f636a_idx',
            old_name='user_cours_user_id_8a2b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='usercourseinteraction',
            new_name='user_course_course__999286_idx',
            old_name='user_cours_course__2b3c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='usercourseinteraction',
            new_name='user_course_interac_eafd0d_idx',
            old_name='user_cours_interac_3c4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='userrecommendationprofile',
            new_name='user_recomm_last_ac_222322_idx',
            old_name='user_recomm_last_ac_0d5f6c_idx',
        ),
        migrations.RenameIndex(
            model_name='userrecommendationprofile',
            new_name='user_recomm_total_l_f2530d_idx',
            old_name='user_recomm_total_l_5e8f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='userviewedcourse',
            new_name='user_viewed_user_pr_6e6349_idx',
            old_name='user_viewed_user_pr_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='userviewedcourse',
            new_name='user_viewed_course__32e7f2_idx',
            old_name='user_viewed_course__2b3c4d_idx',
        ),
    ]
